//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISA.EShop.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MISA.EShop.Core.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi dữ liệu trùng lặp..
        /// </summary>
        public static string ErrorDuplicate {
            get {
                return ResourceManager.GetString("ErrorDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi lọc dữ liệu..
        /// </summary>
        public static string ErrorFilterData {
            get {
                return ResourceManager.GetString("ErrorFilterData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi dữ liệu đầu vào..
        /// </summary>
        public static string ErrorInputData {
            get {
                return ResourceManager.GetString("ErrorInputData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm bản ghi thất bại..
        /// </summary>
        public static string ErrorInsertData {
            get {
                return ResourceManager.GetString("ErrorInsertData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dữ liệu không tồn tại..
        /// </summary>
        public static string ErrorIsNotExist {
            get {
                return ResourceManager.GetString("ErrorIsNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy dữ liệu..
        /// </summary>
        public static string ErrorNotFoundData {
            get {
                return ResourceManager.GetString("ErrorNotFoundData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dữ liệu không được để trống..
        /// </summary>
        public static string ErrorRequiredData {
            get {
                return ResourceManager.GetString("ErrorRequiredData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã cửa hàng đã tồn tại..
        /// </summary>
        public static string ErrorStoreCodeExistData {
            get {
                return ResourceManager.GetString("ErrorStoreCodeExistData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dữ liệu cửa hàng không có..
        /// </summary>
        public static string ErrorStoreNotExistData {
            get {
                return ResourceManager.GetString("ErrorStoreNotExistData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã có lỗi ,vui lòng thử lại..
        /// </summary>
        public static string ErrorTryAgain {
            get {
                return ResourceManager.GetString("ErrorTryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sửa bản ghi thất bại..
        /// </summary>
        public static string ErrorUpdateData {
            get {
                return ResourceManager.GetString("ErrorUpdateData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi hệ thống, liên hệ kỹ thuật MISA..
        /// </summary>
        public static string ExceptionUser {
            get {
                return ResourceManager.GetString("ExceptionUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lấy dữ liệu thành công.
        /// </summary>
        public static string GetDataSuccess {
            get {
                return ResourceManager.GetString("GetDataSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm mới bản ghi thành công..
        /// </summary>
        public static string InsertDataSuccess {
            get {
                return ResourceManager.GetString("InsertDataSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không có nội dung..
        /// </summary>
        public static string NoContentData {
            get {
                return ResourceManager.GetString("NoContentData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy dữ liệu..
        /// </summary>
        public static string NotFoundData {
            get {
                return ResourceManager.GetString("NotFoundData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sửa bản ghi thành công..
        /// </summary>
        public static string UpdateDataSuccess {
            get {
                return ResourceManager.GetString("UpdateDataSuccess", resourceCulture);
            }
        }
    }
}
